sonar.projectKey=Emanuel684_ciencia-datos-prod-riesgo-crediticio
sonar.organization=emanuel684


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=ciencia-datos-prod-riesgo-crediticio
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8